package io.statusmvp.pricebackend.auth;

public enum AuthErrorCode {
  BAD_REQUEST,
  UNAUTHORIZED,
  FORBIDDEN,
  FEATURE_DISABLED,
  PROVIDER_UNAVAILABLE,
  OAUTH_STATE_INVALID,
  OAUTH_STATE_EXPIRED,
  OAUTH_EXCHANGE_FAILED,
  TELEGRAM_VERIFY_FAILED,
  AUTH_CODE_INVALID,
  AUTH_CODE_EXPIRED,
  AUTH_CODE_USED,
  REFRESH_TOKEN_INVALID,
  ACCESS_TOKEN_INVALID,
  ACCESS_TOKEN_EXPIRED,
  BIND_CONFLICT,
  UNBIND_LAST_PROVIDER,
  RATE_LIMITED,
  SYNC_PAYLOAD_INVALID
}

